/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/basicDinghy.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function BasicDinghy(props) {
	const { nodes, materials } = useGLTF('../models/basicDinghy.gltf');
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Spirit_Dinghy.geometry}
				material={materials.basicWood}
				scale={0.01}
			/>
			<mesh
				geometry={nodes.Spirit_Dinghy001.geometry}
				material={materials.basicWoodDagger}
				scale={0.01}
			/>
			<mesh
				geometry={nodes.Spirit_Dinghy002.geometry}
				material={materials.basicWoodPole}
				scale={0.01}
			/>
			<mesh
				geometry={nodes.Spirit_Dinghy003.geometry}
				material={materials.basicWoodBench}
				scale={0.01}
			/>
			<mesh
				geometry={nodes.Spirit_Dinghy004.geometry}
				material={materials.basicWoodRudder}
				scale={0.01}
			/>
		</group>
	);
}

useGLTF.preload('../models/basicDinghy.gltf');
